<?php

/**
 * Debug Bar screen template.
 *
 * It uses Silk Icons created by Mark James and released under Creative Commons Attribution 2.5 License.
 *
 * This file is part of the Nette Framework (http://nette.org)
 * Copyright (c) 2004 David Grudl (http://davidgrudl.com)
 *
 * @param      array     $panels
 * @return     void
 */

namespace Nette\Diagnostics;

use Nette;

?>




<!-- Nette Debug Bar -->


<style id="nette-debug-style" class="nette-debug">
<?php require __DIR__ . '/bar.css' ?>
<?php require __DIR__ . '/dumper.css' ?>
</style>

<!--[if lt IE 8]><style class="nette-debug">
	#nette-debug-bar img { display: none }
	#nette-debug-bar li { border-left: 1px solid #DCD7C8; padding: 0 3px }
	#nette-debug-logo span { background: #edeae0; display: inline }
</style><![endif]-->


<script id="nette-debug-script">
/* <![CDATA[ */
<?php require __DIR__ . '/netteQ.js' ?>
<?php require __DIR__ . '/dumper.js' ?>
<?php require __DIR__ . '/bar.js' ?>

	Nette.Dumper.init();
	Nette.Debug.init();
/* ]]> */
</script>
<!-- /Nette Debug Bar -->
